.gitignore
.vscode/settings.json
build.gradle
eclipse-formatter.xml

vscode currently requires the latest junit (5.6.0) for the java junit
extension to work, thus changing the `build.gradle`
edited workspace settings for vscode to make checkstyle, formatting, andenforce eol to be `\n` not `\r\n`.

Add vscode settings

---

src/main/java/seedu/address/logic/commands/room/AddRoomCommand.java
src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/room/AddRoomCommandParser.java
src/main/java/seedu/address/logic/parser/room/EditRoomCommandParser.java
src/main/java/seedu/address/model/room/Room.java
src/test/java/seedu/address/logic/commands/room/EditRoomCommandTest.java
src/test/java/seedu/address/logic/commands/room/EditRoomDescriptorTest.java
src/test/java/seedu/address/logic/commands/room/RoomCommandTestUtil.java
src/test/java/seedu/address/testutil/room/EditRoomDescriptorBuilder.java
src/test/java/seedu/address/testutil/room/RoomBuilder.java
src/test/java/seedu/address/testutil/room/RoomUtil.java

Blocks access to editing occupancy status of rooms or adding rooms with a specified occupancy status through the GUI. All relevant tests have been updated too.
1. Run SunRez
2. Try to add a room with the occupancy status set (`o/y` or `o/n`). It should throw an error
3. Try to add a room without the occupancy status set. It should work
4. Try to edit that same room by setting an occupancy status as you did in step 2. It should not work
5. Remove the occupancy status. The edit should go through.
Updating the UG and DG

Update rooms prevent set occupancy

---

docs/UserGuide.md

Closes #129 
1. `cd` to `docs/` folder of project.
3. Open the jekyll-hosted user guide in your browser (default address: http://127.0.0.1:4000/UserGuide.html).
4. Look at the `View command history` and `Access command history` entries. They should follow the case formatting of the other entries.

Docs(CommandHistory): Fix UG case inconsistency

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/issue/CloseIssueCommand.java

- Fixes incorrect command word used for closing issue
- Fixes related docs
Check docs
1. cd to docs/ folder of project.
2. Run bundle exec jekyll serve.
3. Open the jekyll-hosted user guide and developer guide in your browser
4. Check for references for icol
Check app
1. Run SunRez
2. Check that `icol` does not work
3. Check that `iclo` works

Change `icol` to `iclo` instead

---

src/main/java/seedu/address/logic/commands/resident/EditResidentCommand.java

Fixes #141 
Launch SunRez
Run clear
Run radd n/John Doe p/98765432 e/johnd@example.com y/1 r/01-234
Run redit 1 y/2
John Doe's year should be updated to 2.
"At least one field to edit must be provided."

Fix(Redit): Fix bug where year of resident can't be edited

---

src/main/java/seedu/address/ui/RoomCard.java

- Displays room occupancy in a more readable way, using "Occupied" and "Not Occupied" instead of "Y" and "N"
Closes #143 
1. Launch SunRez and add a room if there are none
2. Occupancy should be displayed as  "Occupied" and "Not Occupied" instead of "Y" and "N"

Fix(room): Display room occupancy status in a more readable way

---

src/main/java/seedu/address/logic/commands/issue/AddIssueCommand.java

1. Fixes the error message when adding duplicate issues
2. Execute `iadd r/10-100 d/Broken light t/2020/01/12 3:30pm s/pending c/furniture g/HIGH`
3. Execute the same command again
4. There should be an error message "This issue already exists in SunRez"

Fix error message for duplicate issue

---

src/main/java/seedu/address/logic/commands/issue/CloseIssueCommand.java
src/main/java/seedu/address/logic/commands/residentroom/AllocateResidentRoomCommand.java
src/main/java/seedu/address/logic/commands/residentroom/DeallocateResidentRoomCommand.java

This PR fixes the following commands to be undoable: `alloc`, `dealloc`, `iclo`.
Fixes #168 
Fixes #169 
Fixes #170
2. Execute each of the three commands above
3. Try to undo/redo each of them. The undo/redo functionality should work as expected

Fix(UndoRedo): Fix some stateful commands not being undoable

---

src/main/java/seedu/address/model/issue/Issue.java

This PR:
1. Stops tags from being deleted when closing an issue with `iclo`
1. Create a pending issue with tags e.g. `iadd r/10-100 d/Broken room g/Room g/Window`
2. Close the issue with `iclo`
3. The issue should still have the tags

Fix tags being removed when closed

---

src/main/java/seedu/address/model/resident/Name.java
src/main/java/seedu/address/model/resident/Resident.java
src/main/java/seedu/address/model/resident/UniqueResidentList.java

Closes #203 
Closes #232 
`clear`
`radd n/Zender Doe p/98765432 e/johnd@example.com y/1`
`radd n/John Doe p/98765432 e/johnd@example.com y/1`
`radd n/Aaron Doe p/98765432 e/johnd@example.com y/1`
`radd n/Charles Doe p/98765432 e/johnd@example.com y/1`
The residents listed should be sorted alphabetically.

Fix(Sort): Sort residents by alphabetical order

---

docs/UserGuide.md

Add TAG parameter specifications to UG.
Closes #244 
4. Check the TAG subsection of the command parameter section of the UG
Link relevant commands to this subsection.

Close #244: Add TAG parameter specifications

---

docs/UserGuide.md

Fixes #219 
Also removes `[r/ROOM_NUMBER]` from command summary of `redit`

Fix #219: Remove room no. from radd and redit

---

src/main/java/seedu/address/logic/parser/room/DeleteRoomCommandParser.java
src/main/java/seedu/address/logic/parser/room/EditRoomCommandParser.java

- Shows a clearer error message when indices are negative vs out of range
- Closes #165 
- Run `oedit` or `odel` with a negative index. Expect to see "Index is not a non-zero unsigned integer." 
- Previously, it would just show the command usage. Ensure that is not the case now.

Fix(Room): Show better error msg when index is negative in ofind/odel

---

src/main/java/seedu/address/logic/commands/room/AddRoomCommand.java
src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java

Closes #210 by fixing a typo in Add/Edit room command's usage message
1. Run SunRez
2. Type `oadd` and see if `NAME` is removed
3. Check EditRoomCommand's code to see if `NAME` is removed. This cannot be tested visually due to recently discovered bug #293

Fix #236: Fix typo in Add/Edit Room cmd usage message

---

docs/UserGuide.md

This indicates that the insertion order of tags does not guarantee any sort of display order in the UG. This fixes #266 by addressing the tester's concerns.
4. Navigate to the Tags subsection of Command Parameters and observe that Tag behaviour is documented accurately.

Fix #266: Indicate that insertion order of tags do not guarantee any sort of display order

---

docs/UserGuide.md
src/main/java/seedu/address/model/resident/Name.java
src/test/java/seedu/address/model/resident/NameTest.java

Fixes #307 
Only validates alphabetic names.
`radd n/John Doe 123 p/98765432 e/johnd@example.com y/1`
Expected message: `Names should only contain alphabetic characters and spaces, and it should not be blank`

Fix: Change name to accept only alphabets

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/issue/Timestamp.java

Fixes #180 to prevent issues with future timestamps
1. `iadd r/01-234 d/Something broke t/2030/1/1 12:00pm` should show "Timestamps should not be in the future"
2. `iadd r/01-234 d/Something broke t/2021/1/1 12:00pm` should work
3. `iadd r/01-234 d/Something broke` should work

Prevent issues in the future

---

src/main/java/seedu/address/model/issue/Timestamp.java

Fixes #214 to provide better timestamp help message
1. `iadd r/01-234 d/Something broke t/abc` should show a help message detailing each component of a timestamp
2. `iadd r/01-234 d/Something broke t/2021/1/1 1:00pm` should work

Provide better timestamp help message

---

src/main/java/seedu/address/ui/IssueCard.java

Fixes #247 by setting the description label to wrap
1. run `iadd r/01-234 d/ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-1ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-2ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-3ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-4ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-5ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-6ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-7ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-8ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-9ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890-10ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890END`
2. Check that …

Wrap issue description

---

src/main/java/seedu/address/model/tag/Tag.java

- Fixes #237 
- Fixes #328 
- Closes #284 
- by limiting tags to 25 characters
1. run `oadd r/01-235 t/CORRIDOR_NON_AC g/abcdefghijklmnopqrstuvwxyz g/ValidTag`, it should fail and show the 25 character limit error message
2. run `oadd r/01-235 t/CORRIDOR_NON_AC g/abcdefghijklmnopqrstuvwxy g/ValidTag`, it should pass
3. run `oedit 2 g/abcdefghijklmnopqrstuvwxyz`, it should fail and show the 25 character limit error message
4. run `oedit 2 g/abcdefghijklmnopqrstuvwxy`, it should pass
5. run `iadd r/01-235 d/Room spawned suddenly g/abcdefghijklmnopqrstuvwxyz g/Mysterious`, it should fail and show the 25 character limit error message
6. run `iadd r/01-235 d/Room spawned suddenly g/abcdefghijklmnopqrstuvwxy g/Mysterious`, it should pass
7. run `iedit 2 g/abcdefghijklmnopqrstuvwxyz`, it should …

Limit tag size to 25 chars

---

src/main/java/seedu/address/logic/commands/alias/AliasCommand.java
src/main/java/seedu/address/logic/commands/alias/UnaliasCommand.java

Fixes #310 
2. Create an alias. E.g. `alias a/rl cmd/rlist`
3. Test the alias `rl`
3. Undo the alias creation: `undo`
4. Test the alias again `rl`. The alias should not exist now.
5. Redo the alias creation `redo`
6. List the aliases: `aliases`
7. `rl = rlist` should be listed
8. Remove the alias: `unalias a/rl`
9. Test the alias `rl`. It should not exist.
10. Undo the deletion: `undo`
11. Test the alias `rl`. It should work.
12. Redo the deletion: `redo`
13. List the aliases: `aliases`. `rl = rlist` should not be there.

Fix #310: Support alias and unalias commands

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/room/DeleteRoomCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/issue/IssueList.java
src/test/java/seedu/address/logic/commands/ModelStub.java
src/test/java/seedu/address/logic/commands/room/DeleteRoomCommandTest.java
src/test/java/seedu/address/testutil/TypicalIndexes.java
src/test/java/seedu/address/testutil/issue/TypicalIssues.java

Closes #224 by blocking usage of odel unless all associated issues with it are deleted
- Fixes #146 
1. Add a bunch of issues to a room
2. Try to delete the room. It should fail
3. Try to delete a room without issues. It should not fail
4. Do anything else to try and break this

Fix #236: Prevent room deletion if there are issues associated with it

---

docs/UserGuide.md

Closes #280 
4. Check that the Quick Start section is just after Introduction and before SunRez UI

Docs(UG): Move Quick Start section to just after intro

---

src/main/java/seedu/address/model/issue/Description.java
src/test/java/seedu/address/model/issue/DescriptionTest.java

- Fixes #249 by limiting description to `[A-Za-z0-9][A-Za-z0-9 ]*`
1. run `iadd r/01-234 d/ABCDEFGHIJKLMNOPQRSTUWXYZ abcdefghijklmnopqrstuvwxyz 1234567890`, it should work
2. run `iadd r/01-234 d/ABCDEFGHIJKLMNOPQRSTUWXYZ abcdefghijklmnopqrstuvwxyz 1234567890-` or any string with non alphanum and not space, should fail and show: 
>Descriptions should only contain alphanumeric characters and spaces, and it should not be blank. Leading and trailing whitespaces will be trimmed."
1. run `iedit 1 d/ABCDEFGHIJKLMNOPQRSTUWXYZ abcdefghijklmnopqrstuvwxyz 1234567890`, it should work
2. run `iadd 1 d/ABCDEFGHIJKLMNOPQRSTUWXYZ abcdefghijklmnopqrstuvwxyz 1234567890-` or any string with non alphanum and not space, should fail and show: 
>Descriptions should only contain alphanumeric characters and …

Limit description characters

---

docs/DeveloperGuide.md

This PR:
1. removes placeholder documentation from the DG
2. updates non-functional requirements in the DG
3. adds manual test cases for command history
4. adds manual test cases for undo/redo
Closes #351 
4. Check that the DG has the changes listed above

Docs(DG): Add manual test cases for command history and undo/redo

---

docs/DeveloperGuide.md

This PR:
1. updates the links in the architecture section (to point to our repo)
2. adds introduction, audience and diagrams sections
3. adds section explaining AddressBook legacy
4. Check that the DG has the changes listed above

Docs(DG): Add introduction sections

---

src/main/java/seedu/address/model/issue/RoomNumber.java

- Updates the room number regex for issue to be the same as room
- Fixes #367 
- Fixes #366 
1. Run `iadd r/00-000 d/desp`, it should show the error message "Room numbers should be formatted as such: XY-ABC, where XY can be any pair of digits except 00, and ABC can be any 3 digits."
2. Run `iadd r/01-234/ d/desp`, it should work

Update room number regex

---

docs/DeveloperGuide.md

Closes #350 
Adds manual testing guide to Developer Guide for residents
cd to docs/ folder of the project.
Run bundle exec jekyll serve.
Open the jekyll-hosted website in your browser (default address: http://127.0.0.1:4000).
Check that the DG has the changes listed above

Doc: Add Manual Testing 

---

docs/DeveloperGuide.md

Closes #353
Ensures that resident related use cases are updated. 
cd to docs/ folder of the project.
Run bundle exec jekyll serve.
Open the jekyll-hosted website in your browser (default address: http://127.0.0.1:4000).
Check that the DG has the changes listed above under the UC-19 and UC-20 section

Docs(UC): Update use cases for Alloc and Dealloc

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
src/test/java/seedu/address/logic/commands/room/EditRoomCommandTest.java

This PR:
1. Closes #387 blocking the editing of rooms that have associated issues
1. Run SunRez with the sample data
2. Try editing or deleting a room that is tied to an issue. It should fail
3. Delete the issue and try editing the room again. It should succeed.
4. Recreate the instructions in #387 and it should also fail

Fix(Room): Block editing rooms with associated issues

---

src/test/java/seedu/address/testutil/TypicalCommandHistoryEntries.java

This PR should fix the test case `PlainTextCommandHistoryStorageTest#saveAndRead_allInOrder_success` from occasionally failing.
Not deterministic, but see if this test case fails randomly either locally or during automated tests on GitHub.

Fix: Prevent getRandomEntry from generating an empty string

---

docs/DeveloperGuide.md

Adds a diagram note to the Logic class diagram located in the architecture section of the DG, describing the placeholder classes.
4. Check that the DG has the changes listed above

Docs(DG): Add logic class diagram note

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java

This PR:
1. Closes #405 blocking the editing of room numbers for rooms that have associated issues
1. Run SunRez with the sample data
2. Try editing the room number of a room with an associated issue. It should fail
3. Try editing the room type or tags of that room. It should succeed.
4. Delete the issues that the room is tied to
5. Try editing the room number of that room. It should succeed.

Fix(Room): Block editing room with issues if room number changes

---

docs/UserGuide.md

This PR:
1. Closes #430 by removing extraneous qualifications of `INDEX`
2. Fixes a typo where I referred to a room list as a resident list

Fix(UG): Standarise use of INDEX and fix typos

---

docs/DevOps.md

This PR fixes the code coverage link in the [DevOps guide](https://ay2021s2-cs2103-t14-1.github.io/tp/DevOps.html).
4. Go to `Developer Guide` -> `Documentation, logging, testing, configuration, dev-ops` -> `DevOps guide`
5. Check the code coverage badge on the page. It should link to the correct code coverage dashboard.

Docs(DevOps): Fix codecov link

---

docs/DeveloperGuide.md

This PR adds the effort section to the DG.
4. Go to the DG and scroll to the bottom. See if it makes sense and is accurate.
Written by @benedictkhoomw and @DrWala, reviewed by entire team.

Docs(DG): Add effort section

---

docs/_includes/head.html

This PR fixes the favicon to show up in everyone's PPPs.
4. Go to `About Us` then click on the `portfolio` links for each team member. The favicon should show up.

Docs(Favicon): Fix favicon in PPPs
