docs/DeveloperGuide.md

Update Developer guide

---

src/main/java/seedu/address/ui/HelpWindow.java

As discussed, let's update our user guide url

Update user guide url

---

src/main/java/seedu/address/logic/commands/room/AddRoomCommand.java

fix(add room): update usage message to reflect accurate room type

---

src/main/java/seedu/address/logic/commands/resident/AddResidentCommand.java
src/main/java/seedu/address/logic/commands/resident/EditResidentCommand.java
src/main/java/seedu/address/model/resident/Resident.java
src/main/java/seedu/address/ui/ResidentCard.java

Fixes #67 
1. Fix the resident example message so that the example works.
2. Format the resident error message so that its on a new line.

Fix resident example message

---

src/main/java/seedu/address/logic/commands/issue/AddIssueCommand.java

Fix iadd usage message

---

docs/UserGuide.md

Command History: Add missing UG entry

---

src/main/java/seedu/address/logic/commands/issue/AddIssueCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/issue/Issue.java
src/main/java/seedu/address/model/issue/IssueList.java
src/main/java/seedu/address/model/issue/Timestamp.java

feat(issue): Sort issues ascending via timestamp

---

docs/DeveloperGuide.md

Fixes #60
Also fixes `e.g` to `e.g.`

Fix DG Use Case Formatting

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/alias/AliasCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java

This PR fixes duplicate prefixes error for alias command

Fix duplicate prefixes error

---

src/main/resources/view/MainWindow.fxml

Change app title to "SunRez"

---

src/main/java/seedu/address/MainApp.java

Fix timestamp parse by setting locale

---

src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/model/issue/Description.java
src/main/java/seedu/address/model/issue/Issue.java
src/main/java/seedu/address/model/issue/IssueList.java
src/main/java/seedu/address/model/issue/exceptions/DuplicateIssueException.java
src/test/java/seedu/address/model/issue/CategoryTest.java
src/test/java/seedu/address/model/issue/DescriptionTest.java
src/test/java/seedu/address/model/issue/IssueListTest.java
src/test/java/seedu/address/model/issue/IssueTest.java
src/test/java/seedu/address/model/issue/RoomNumberContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/issue/RoomNumberTest.java
src/test/java/seedu/address/model/issue/StatusTest.java
src/test/java/seedu/address/model/issue/TimestampTest.java
src/test/java/seedu/address/testutil/issue/IssueBuilder.java
src/test/java/seedu/address/testutil/issue/TypicalIssues.java

Increases code coverage for commands and models associated with the issue class
Closes #99 
1. Checkout the project
2. Run tests for the project
3. Ensure all tests are passing

Add issue tests

---

src/main/java/seedu/address/logic/commands/issue/CloseIssueCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/issue/CloseIssueCommandParser.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/issue/Issue.java
src/main/java/seedu/address/model/issue/IssueList.java
src/main/java/seedu/address/model/issue/Status.java

This PR
1. adds the close issue command to set an issue's status to 'Closed'
Closes #87 
1. Create a new issue or use an existing issue that is still 'Pending'
2. Test the close issue command with `icol INDEX` where `INDEX` is the index of the issue to be closed in the displayed list of issues
3. The issue should be closed
4. If `icol` is used with an issue that is already closed, a message will be shown to the user detailing that.

Add close issue command

---

.vscode/launch.json

This PR
1. adds a launch config for VS Code with assertions enabled
1. Add a `assert false` to test assertion error
2. Launch SunRez from VS Code with the new launch config
3. trigger the `assert false` statement

Add launch.json with assertions for VS Code

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/issue/AddIssueCommand.java
src/main/java/seedu/address/logic/commands/issue/EditIssueCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/issue/AddIssueCommandParser.java
src/main/java/seedu/address/logic/parser/issue/EditIssueCommandParser.java
src/main/java/seedu/address/model/issue/Issue.java
src/main/java/seedu/address/storage/JsonAdaptedIssue.java
src/main/java/seedu/address/ui/IssueCard.java
src/main/resources/view/IssueListCard.fxml
src/test/java/seedu/address/model/issue/StatusTest.java

This PR
1. adds tag issue support
Closes #90 
1. Launch SunRez.
2. Execute the `iadd r/10-100 d/Broken light t/2020/01/12 3:30pm s/pending c/furniture g/HIGH` command. You should see the issue added with the tag `HIGH`.

Add tag issue support

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/commons/core/Config.java
src/main/java/seedu/address/model/issue/Timestamp.java

Fix the timestamp related test cases by setting the locale used in the DateTimeFormatter.
1. Checkout the project
2. Run tests for the project
3. Ensure all tests are passing (especially for timestamp related test cases)

Fix locale issue for test

---

docs/UserGuide.md

Doc(Name): Add statement that unique identifier of resident is NAME

---

build.gradle
src/main/java/seedu/address/commons/core/LogsCenter.java
src/main/java/seedu/address/model/UserPrefs.java
src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java

This PR renames output files (JAR, log, data files) from e.g. `addressbook.jar` to `sunrez.jar`
Closes #105 
1. Build the shadowJar using gradle
2. The output file should be named `sunrez.jar`
3. Copy and paste that file to some testing directory
4. Run `sunrez.jar`, either by double-clicking or via a CLI: `java -jar ./sunrez.jar`
5. Execute the command `rdel 1`
6. Exit the application
7. Observe the names of the files generated by SunRez. None of them should be named addressbook

Rename output files

---

src/main/java/seedu/address/logic/commands/CommandResult.java

Closes #125 
1. See `Files Changed`
2. Check that the boolean names follow the coding convention.

Fix(CommandResult): Fix Code Style

---

docs/UserGuide.md

This PR:
1. adds sections to categorize the features in the UG
2. updates the data transfer instructions in the Q&A

Docs(UG): Add feature sections and update data transfer instructions

---

docs/UserGuide.md

This PR adds the clear command to the UG

Docs(UG): Add clear command

---

src/main/java/seedu/address/model/util/SampleDataUtil.java

This PR updates the sample data with sample issues, rooms and unassigned residents.
Closes #171
1. Delete `data/sunrez.json`
2. Launch SunRez
3. Observe the sample data

SampleDataUtil: Update sample data

---

docs/UserGuide.md

This PR:
* adds a parameters section with placeholders
* updates the view command history entry to follow
* updates TYPE to ROOM_TYPE
* updates ROOM and ROOM_NO to ROOM_NUMBER for consistency
Closes #276

UG: Add parameters section

---

src/main/resources/view/MainWindow.fxml

Increases window min height
Fixes #217
2. Shrink the window as small as you can
3. See if any part of the UI cuts off

Fix #217: Increase window min height

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/issue/EditIssueCommand.java
src/main/java/seedu/address/logic/commands/resident/AddResidentCommand.java
src/main/java/seedu/address/logic/commands/resident/EditResidentCommand.java
src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
src/main/java/seedu/address/model/ModelManager.java

This PR change string references of address book to SunRez, including those found in command error messages.
Fixes #201
2. Try to find user-visible traces of Address Book in the logs or wherever.
3. Search the files in the codebase for strings containing "address book". There should be none left.

Fix #201: Change string references of address book to SunRez

---

docs/UserGuide.md

Closes #255
4. Navigate to `Introduction` section.
5. Observe the use of `Graphical User Interface (GUI)`.
6. Be happy.

Fix #255: Add meaning of GUI to intro

---

src/test/java/seedu/address/logic/commands/room/RoomCommandTestUtil.java
src/test/java/seedu/address/model/room/RoomNumberOrTagsContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/room/RoomNumberTest.java
src/test/java/seedu/address/model/room/RoomOccupancyTest.java
src/test/java/seedu/address/model/room/RoomTest.java
src/test/java/seedu/address/model/room/UniqueRoomListTest.java

- Implement tests for the fields of Room
- Checkout the PR and run the tests. All tests should pass.
- Observe code coverage increase in jacoco test report for model room

Implement tests for Room's fields

---

docs/UserGuide.md
src/main/java/seedu/address/model/room/Room.java
src/main/java/seedu/address/model/room/RoomNumber.java
src/main/java/seedu/address/model/room/UniqueRoomList.java

Closes #236 by sorting all rooms in all views by room number, and updates this behaviour in the UG.
1. Run a bunch of CRUD + find commands on the rooms
2. Ensure that they are always sorted in ascending order.

Fix #236: Sort rooms by room number for all views

---

src/main/resources/view/MainWindow.fxml

Closes #253 by adding headers to the columns
2. Mess around with the window size and other UI elements, then see if the column headers still look okay (e.g. at min and max resolution).

Close #253: Add column headers

---

src/main/resources/view/IssueListCard.fxml
src/main/resources/view/ResidentListCard.fxml
src/main/resources/view/RoomListCard.fxml

Closes #226 by decreasing minimum card size
2. Insert residents, rooms and issues of various sizes (long descriptions, many tags, no tags, etc.) Also, mess around with the window size and other UI elements and see if things still look okay.

Close #226: Decrease minimum card size

---

src/main/java/seedu/address/commons/core/AliasMapping.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/alias/AliasCommand.java
src/main/java/seedu/address/logic/commands/alias/UnaliasCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyAddressBook.java
src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
src/main/java/seedu/address/model/UserPrefs.java
src/main/java/seedu/address/storage/JsonAdaptedAlias.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
src/test/data/JsonSerializableAddressBookTest/duplicateResidentAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidResidentAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalResidentsAddressBook.json
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/model/AddressBookTest.java

Migrate alias support to AddressBook. 
1. Test some alias command.
2. Check if the json file is updated.
3. Exit the app and open again.
4. Check if the alias data is still there.

Migrate alias to AddressBook

---

docs/UserGuide.md
src/main/java/seedu/address/commons/core/AliasMapping.java
src/main/java/seedu/address/logic/commands/alias/AliasCommand.java
src/test/java/seedu/address/logic/commands/alias/AliasCommandTest.java

Update alias success message when a new alias is added vs when an existing alias is updated.
Fixes #272
1. Input `alias a/a cmd/help`.
2. Input `alias a/a cmd/clear`. The success message should be `Alias updated: a`.
3. Enter more alias command.
4. Input `aliases`. The aliases should be in alphabetical order.

Update alias success message and documentation

---

src/main/java/seedu/address/model/issue/Issue.java

Fixes #89 by sorting it by status (pending then closed) followed by timestamp
1. Run SunRez and check that the existing data for issues (if any) is sorted pending then closed
- If same status then sort by timestamp
2. add issues with timestamp between min existing timestamp and max existing timestamp
3. add issues with current time as timestamp (by not specifying timestamp parameter)
4. add issues with timestamp earlier than any other issues
3. edit an issue to test same equivalence partitions like step 2 - 4

Fix issues sort by status then timestamp

---

src/main/resources/view/ResultDisplay.fxml

Adds text wrap to the result box.
Close #303
2. Enter a long command. E.g. `iadd r/01-234 d/Broken light s/pending c/furniture g/MMMMMMMMMMMMMMMMMMMMMM0 g/MMMMMMMMMMMMMMMMMMMMMM1 g/MMMMMMMMMMMMMMMMMMMMMM2 g/MMMMMMMMMMMMMMMMMMMMMM3 g/MMMMMMMMMMMMMMMMMMMMMM4 g/MMMMMMMMMMMMMMMMMMMMMM5 g/MMMMMMMMMMMMMMMMMMMMMM6 g/MMMMMMMMMMMMMMMMMMMMMM7 g/MMMMMMMMMMMMMMMMMMMMMM8 g/MMMMMMMMMMMMMMMMMMMMMM9 g/MMMMMMMMMMMMMMMMMMMMMM10 g/MMMMMMMMMMMMMMMMMMMMMM11 g/MMMMMMMMMMMMMMMMMMMMMM12 g/MMMMMMMMMMMMMMMMMMMMMM13 g/MMMMMMMMMMMMMMMMMMMMMM14 g/MMMMMMMMMMMMMMMMMMMMMM15 g/MMMMMMMMMMMMMMMMMMMMMM16 g/MMMMMMMMMMMMMMMMMMMMMM17 g/MMMMMMMMMMMMMMMMMMMMMM18 g/MMMMMMMMMMMMMMMMMMMMMM19 `
3. See that the text in the result box is not truncated.

Close #303: Add text wrap to result box

---

docs/AboutUs.md

Closes #198 
4. Check that the About Us page has the changes listed above

Close #198: Update Benedict's responsibilities in About Us

---

src/main/java/seedu/address/ui/IssueCard.java
src/main/resources/view/IssueListCard.fxml
src/main/resources/view/RoomListCard.fxml

- Fixes #331 
- Run the usual CRUD and ensure UI does not look wrong (all data in the cards are correct, wrapping still works)

CodeQuality: Separate logic and display stuff, update placeholder text

---

src/main/java/seedu/address/commons/core/Alias.java
src/main/java/seedu/address/commons/core/AliasMapping.java
src/main/java/seedu/address/logic/commands/alias/AliasCommand.java
src/main/java/seedu/address/logic/commands/alias/ListAliasCommand.java
src/main/java/seedu/address/logic/commands/alias/UnaliasCommand.java
src/main/java/seedu/address/logic/parser/alias/AliasCommandParser.java
src/main/java/seedu/address/logic/parser/alias/UnaliasCommandParser.java
src/test/java/seedu/address/logic/commands/alias/AliasCommandTest.java
src/test/java/seedu/address/logic/commands/alias/ListAliasCommandTest.java
src/test/java/seedu/address/logic/commands/alias/UnaliasCommandTest.java
src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/testutil/alias/AliasUtil.java

1. Adds assertions and logging for alias
2. Closes #100 #184 
1. Check that all test cases pass

Add test case, assertion and logging

---

docs/_sass/minima/_base.scss

Closes #313 
4. Check that the header when you print the UG and DG say SunRez

Fix(Docs): Update base styles with correct header

---

docs/UserGuide.md

Fix(UG): Update room params to be code blocks

---

src/main/java/seedu/address/logic/commands/residentroom/AllocateResidentRoomCommand.java
src/main/java/seedu/address/logic/commands/residentroom/DeallocateResidentRoomCommand.java

Closes #389 
Standardise allocation and deallocation error messages
`alloc`
Expected Message
`dealloc`

Change alloc dealloc error message

---

src/main/java/seedu/address/model/issue/Issue.java

- Removes tags check from issue's equals
Fixes #393 
1. run `iadd r/01-234 d/abc t/2020/01/01 12:15pm s/pending c/Alphabets g/A`
2. run `iadd r/01-234 d/abc t/2020/01/01 12:15pm s/pending c/Alphabets g/B`, it should fail
3. run `iadd r/01-234 d/abc t/2020/01/01 12:15pm s/pending c/Alphabetz g/A`, it should add

Remove Tags from issue equals

---

docs/DeveloperGuide.md

- Closes #354
- Removes user stories we don't need
- Updates the word "task" to "issue"
- Ensures all user stories have all 3 parts
- Phrasing for the 3 "find" stories. Are they ok? Are they too complex?
4. Check that the DG has the changes listed above under the "User Stories" section

Fix(DG): Update user story formatting

---

docs/team/drwala.md

Docs(PPP): Add contribution

---

src/main/java/seedu/address/storage/JsonSerializableAddressBook.java

- Checks for duplicate issues when loading from save file
Fixes #397 
- Edit the save file to contain 2 duplicate issues (This PR currently include tags in issue `equals`)
- Start SunRez, it should not crash

Fix loading duplicate issues

---

docs/DeveloperGuide.md

Fixes Issue Class image link in UG
Fixes #274
1. Check with jekyll that the issue class diagram shows

Fix issue class link in UG

---

docs/DeveloperGuide.md

Closes #385 
4. Check that the DG has the changes listed above and makes sense.

Docs(DG): Add sub-section explaining diagram color scheme

---

docs/UserGuide.md

Refactor: Remove overlap

---

src/main/java/seedu/address/model/util/SampleDataUtil.java

Refactor(Sample Data): Add resident rooms to sample data

---

docs/DeveloperGuide.md

This PR adds "Application Programming Interface" on the first use of "API" in the DG.
4. Check that the DG has the changes listed above

Docs(DG): Add full-length version of API on first use

---

src/test/java/seedu/address/logic/commands/room/DeleteRoomCommandTest.java
src/test/java/seedu/address/logic/commands/room/EditRoomCommandTest.java
src/test/java/seedu/address/model/room/RoomNumberTest.java
src/test/java/seedu/address/storage/room/JsonAdaptedRoomTest.java

Increases test coverage for room feature
Checkout this PR and run tests. Observe that there are more tests now, and coverage has increased.

Test(Room): Increase room test coverage

---

docs/team/stein414.md

Updates Ian's PPP with more information
1. Run with jekyll and check that the changes are reflect

Docs(PPP): Update Ian's PPP

---

docs/AboutUs.md

AboutUs: Update names to match Luminus

---

src/test/java/seedu/address/logic/parser/issue/AddIssueCommandParserTest.java
src/test/java/seedu/address/model/issue/IssueContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/issue/RoomNumberTest.java
src/test/java/seedu/address/testutil/issue/EditIssueDescriptorBuilder.java
src/test/java/seedu/address/testutil/issue/IssueBuilder.java

Updates test comments and renames 1 file
1. Checkout the PR
2. Run the tests, all tests should be passing

Test(Issue): Update test comments

---

docs/team/drwala.md

Fix(PPP): Update PPP

---

docs/team/stein414.md

Adds more links to the PRs relevant to the point
1. Run jekyll and check that the changes are reflected

Docs(PPP): Add more PR references

---

docs/team/benedictkhoomw.md

This PR standardizes the intro of Benedict's PPP.
4. Go to `About Us` then click on the `portfolio` link under Benedict's profile.
5. Check that the page is updated.

Docs(PPP): Update Benedict's PPP

---

docs/team/drwala.md

Fix(PPP): Update reposense link

---

docs/UserGuide.md

This PR updates user instructions to transfer SunRez data from one computer to another.
4. Open the UG and check that the updated instructions (under Q&A) make sense.

Docs(UG): Update data transfer instructions

---

src/test/java/seedu/address/commons/util/MathUtilTest.java
src/test/java/seedu/address/logic/commandhistory/SuppliedCommandHistorySelectorTest.java
src/test/java/seedu/address/logic/commands/ViewHistoryCommandTest.java
src/test/java/seedu/address/logic/parser/ViewHistoryCommandParserTest.java
src/test/java/seedu/address/model/commandhistory/CommandHistoryEntryTest.java
src/test/java/seedu/address/model/commandhistory/CommandHistoryTest.java
src/test/java/seedu/address/storage/commandhistory/PlainTextCommandHistoryStorageTest.java
src/test/java/seedu/address/testutil/TypicalCommandHistoryEntries.java

This PR updates command history tests and their comments.
Check that all tests are passing.

Update command history tests

---

src/main/java/seedu/address/logic/commands/room/AddRoomCommand.java
src/main/java/seedu/address/logic/commands/room/DeleteRoomCommand.java
src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
src/main/java/seedu/address/logic/commands/room/FindRoomCommand.java
src/main/java/seedu/address/logic/commands/room/ListRoomCommand.java
src/main/java/seedu/address/logic/parser/room/AddRoomCommandParser.java
src/main/java/seedu/address/logic/parser/room/DeleteRoomCommandParser.java
src/main/java/seedu/address/logic/parser/room/EditRoomCommandParser.java
src/main/java/seedu/address/logic/parser/room/FindRoomCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/room/IsOccupied.java
src/main/java/seedu/address/model/room/Room.java
src/main/java/seedu/address/model/room/RoomNumber.java
src/main/java/seedu/address/model/room/RoomType.java
src/main/java/seedu/address/model/room/RoomTypeOptions.java
src/main/java/seedu/address/model/room/UniqueRoomList.java
src/test/java/seedu/address/logic/commands/CommandResultTest.java
src/test/java/seedu/address/logic/commands/room/AddRoomCommandTest.java
src/test/java/seedu/address/logic/commands/room/DeleteRoomCommandTest.java
src/test/java/seedu/address/logic/commands/room/EditRoomCommandTest.java
src/test/java/seedu/address/logic/commands/room/EditRoomDescriptorTest.java
src/test/java/seedu/address/logic/commands/room/ListRoomCommandTest.java
src/test/java/seedu/address/logic/commands/room/RoomCommandTestUtil.java
src/test/java/seedu/address/model/room/RoomNumberTest.java
src/test/java/seedu/address/model/room/RoomOccupancyTest.java
src/test/java/seedu/address/model/room/RoomTest.java
src/test/java/seedu/address/model/room/UniqueRoomListTest.java

Increases JavaDoc coverage for the Room sections of the code.

Docs(Room): Update JavaDocs for Room
